(function(){
  const money = v => new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(Number(v||0));
  const esc = v => String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
  function getData(){ try { return JSON.parse(localStorage.getItem('crm-demo-data')) || {}; } catch(e){ return {}; } }
  function render(){
    const data=getData(), app=document.getElementById('app'); if(!app) return;
    const deals=data.deals||[], leads=data.leads||[], tasks=data.tasks||[], contacts=data.contacts||[], companies=data.companies||[], activities=data.activities||[];
    const open=deals.filter(d=>!['Won','Lost'].includes(d.stage));
    const pipeline=open.reduce((s,d)=>s+Number(d.value||0),0);
    const won=deals.filter(d=>d.stage==='Won').reduce((s,d)=>s+Number(d.value||0),0);
    const forecast=open.reduce((s,d)=>s+Number(d.value||0)*(d.stage==='Negotiation'?.8:d.stage==='Proposal'?.6:d.stage==='Qualified'?.35:.15),0);
    const qualified=leads.filter(l=>['Qualified','Won'].includes(l.status)).length;
    const conversion=leads.length?Math.round(qualified/leads.length*100):0;
    const openTasks=tasks.filter(t=>t.status!=='Done').length;
    const highTasks=tasks.filter(t=>t.status!=='Done'&&['High','Urgent'].includes(t.priority)).length;
    const stages=['New','Qualified','Proposal','Negotiation','Won'];
    const stage=stages.map(x=>({name:x,count:deals.filter(d=>d.stage===x).length,value:deals.filter(d=>d.stage===x).reduce((s,d)=>s+Number(d.value||0),0)}));
    const top=companies.map(c=>({c,v:deals.filter(d=>d.company===c.name&&!['Lost'].includes(d.stage)).reduce((s,d)=>s+Number(d.value||0),0)})).sort((a,b)=>b.v-a.v).slice(0,5);
    app.innerHTML=`<div class="dashboard-head"><div><p class="eyebrow">SALES COMMAND CENTER</p><h2>Know what needs attention.</h2><p>Revenue, pipeline, customers and priorities — together.</p></div><div class="row-actions"><button class="secondary-btn" data-view="deals">View pipeline</button><button class="primary-btn" data-add="deals">+ Add opportunity</button></div></div>
    <div class="stats"><div class="card"><div class="stat-label">Open pipeline</div><div class="stat-value">${money(pipeline)}</div><div class="stat-meta">${open.length} active opportunities</div></div><div class="card"><div class="stat-label">Weighted forecast</div><div class="stat-value">${money(forecast)}</div><div class="stat-meta">Probability-adjusted</div></div><div class="card"><div class="stat-label">Won revenue</div><div class="stat-value">${money(won)}</div><div class="stat-meta">${deals.filter(d=>d.stage==='Won').length} closed wins</div></div><div class="card"><div class="stat-label">Lead conversion</div><div class="stat-value">${conversion}%</div><div class="stat-meta">${qualified} qualified / won leads</div></div></div>
    <div class="dashboard-grid"><section class="panel"><div class="panel-head"><div><h2>Pipeline by stage</h2><span class="panel-subtitle">Where revenue is moving</span></div><button class="text-btn" data-view="deals">Manage</button></div><div class="pipeline">${stage.map(s=>`<div><div class="stage-top"><span>${s.name}</span><strong>${s.count}</strong></div><div class="stage-bar"><span style="width:${pipeline?Math.max(4,Math.min(100,s.value/pipeline*100)):0}%"></span></div><div class="stage-value">${money(s.value)}</div></div>`).join('')}</div></section>
    <section class="panel"><div class="panel-head"><div><h2>Priority queue</h2><span class="panel-subtitle">${highTasks} high-priority task${highTasks===1?'':'s'}</span></div><button class="text-btn" data-view="tasks">Open tasks</button></div><div class="task-list">${tasks.filter(t=>t.status!=='Done').slice(0,5).map(t=>`<div class="task-row"><span class="task-dot"></span><div><strong>${esc(t.title)}</strong><small>${esc(t.due||'No due date')} · ${esc(t.owner||'Unassigned')}</small></div><span class="badge">${esc(t.priority||'Normal')}</span></div>`).join('')||'<div class="empty">No open tasks.</div>'}</div></section></div>
    <div class="dashboard-grid lower-grid"><section class="panel"><div class="panel-head"><div><h2>Top accounts</h2><span class="panel-subtitle">Open commercial value by company</span></div><button class="text-btn" data-view="companies">Accounts</button></div>${top.length?`<table><thead><tr><th>Company</th><th>Contacts</th><th>Open value</th></tr></thead><tbody>${top.map(x=>`<tr><td><strong>${esc(x.c.name)}</strong></td><td>${contacts.filter(c=>c.company===x.c.name).length}</td><td>${money(x.v)}</td></tr>`).join('')}</tbody></table>`:'<div class="empty">No account data yet.</div>'}</section>
    <section class="panel"><div class="panel-head"><div><h2>Recent activity</h2><span class="panel-subtitle">Latest customer and sales events</span></div><button class="text-btn" data-view="tasks">Activities</button></div><div class="task-list">${activities.slice(0,5).map(a=>`<div class="task-row"><span class="task-dot"></span><div><strong>${esc(a.subject||a.text||'Activity')}</strong><small>${esc(a.relatedName||a.time||a.date||'')}</small></div><span class="badge">${esc(a.type||'Activity')}</span></div>`).join('')||'<div class="empty">No recent activity.</div>'}</div></section></div>
    <div class="panel"><div class="panel-head"><div><h2>CRM health</h2><span class="panel-subtitle">Current operating picture</span></div></div><div class="company-metrics"><div><strong>${companies.length}</strong><span>Accounts</span></div><div><strong>${contacts.length}</strong><span>Contacts</span></div><div><strong>${leads.length}</strong><span>Leads</span></div><div><strong>${deals.length}</strong><span>Opportunities</span></div><div><strong>${openTasks}</strong><span>Open tasks</span></div></div></div>`;
  }
  document.addEventListener('click',function(e){ const nav=e.target.closest('[data-view="dashboard"]'); if(nav){ e.preventDefault(); e.stopImmediatePropagation(); document.querySelectorAll('.nav-item').forEach(x=>x.classList.remove('active')); nav.classList.add('active'); const t=document.getElementById('page-title'); if(t)t.textContent='Dashboard'; render(); } },true);
  window.renderDashboardV09=render;
  document.addEventListener('DOMContentLoaded',()=>{ if(document.querySelector('[data-view="dashboard"]')?.classList.contains('active')) setTimeout(render,0); });
})();